Improving ReadMe and adding comments to the code
GarretTomlin/Extodan pull request #27
Opened 2023-08-09 15:29 UTC by jojosuelobo

For the project's ReadMe, its structure was improved in a basic way, for a better visualization. In addition, some more comments were added to the code in the hope of improving the understanding of its logic for future uses and maintenance.

2023-08-09 16:35 UTC, GarretTomlin requested changes

2023-08-09 16:35 UTC, GarretTomlin commented on internal/errors/errors.go
> +    Message   string         // A human-readable error message.
the message is self documented

2023-08-09 16:35 UTC, GarretTomlin commented on internal/errors/errors.go
> +    Path string // The path associated with the I/O validation error.
each individual variable don't need to be documented because the function itself is already documented

2023-08-09 17:24 UTC, jojosuelobo commented
The quoted tweaks have been changed to remove comments on self documented variables

2023-08-12 19:30 UTC, GarretTomlin commented
@jojosuelobo  you broke something the test fail

2023-08-13 14:21 UTC, closed without merging